#4일차

0.복습

In [11]:
#리스트 > 인덱싱, 슬라이싱 가능, 시퀀스자료형
list1 = [1,2,3,4,5]
print(list1, type(list1))
print(list1[1], list1[-4])
print(list1[1:4])

list2 = ['가','나','다']
print(list2[2])

list3 = [5,6,7,8,9]
print(list1 + list3)
print(list3 * 3)

list4 = [1.1, True, '가', 3.3, '나', 6.5, 'python']
print(list4 )
print(True in list4)
print(False in list4)
print(False not in list4)

[1, 2, 3, 4, 5] <class 'list'>
2 2
[2, 3, 4]
다
[1, 2, 3, 4, 5, 5, 6, 7, 8, 9]
[5, 6, 7, 8, 9, 5, 6, 7, 8, 9, 5, 6, 7, 8, 9]
[1.1, True, '가', 3.3, '나', 6.5, 'python']
True
False
True

In [16]:
#튜플 > 인덱싱, 슬라이싱 가능 , 시퀀스자료형
tuple1 =  (1,2,3, "가","a", "B", 1.1, 1.4)
print(tuple1, type(tuple1))

tuple2 = ('가', '나')
print(tuple1 + tuple2)
print(tuple2 + tuple1)

print(tuple1[6])

#print(tuple2 in '나') #TypeError: 'in <string>' requires string as left operand, not tuple 찾을 문자열 in 튜플명 / 리스트명 / 변수명 순서로 작성함
print('나' in tuple2)

(1, 2, 3, '가', 'a', 'B', 1.1, 1.4) <class 'tuple'>
(1, 2, 3, '가', 'a', 'B', 1.1, 1.4, '가', '나')
('가', '나', 1, 2, 3, '가', 'a', 'B', 1.1, 1.4)
1.1
True

In [18]:
#세트 > 중복값허용x , 인덱스,슬라이싱x, 비시퀀스자료형
set1 = {1,2,3,4,1,2,'가', 'APPLE'}
print(set1, type(set1)) # 중복된 값이 허용되지 않음
#print(set1[3]) TypeError: 'set' object is not subscriptable 인덱스,슬라이싱허용 x

{1, 2, 3, 4, '가', 'APPLE'} <class 'set'>

TypeError: ignored

In [26]:
#딕셔너리 = 사전 비시퀀스자료형 > 인덱스 대신에 key로 찾게됨
dict1 = {'a':'apple', 'b':'banana'}
print(dict1, type(dict1))

dict2 = {"1반":['짱구', '맹구'], "2반":["철수", "유리"]}
print(dict2, type(dict2))

print(dict2['1반'])
print(dict2['2반'])
print(dict1['b'])

{'a': 'apple', 'b': 'banana'} <class 'dict'>
{'1반': ['짱구', '맹구'], '2반': ['철수', '유리']} <class 'dict'>
['짱구', '맹구']
['철수', '유리']
banana

1.조건문 if문, if~else문

0) 조건문을 위한 논리연산

In [39]:
#and 연산 > 두 값이 모두 True일 때만 True를 반환
print(True and True)
print(True and False)
print(False and True)
print(False and False)

num1 = 40
print((num1 > 30) and (num1 < 50))

True
False
False
False
True

In [44]:
#or 연산 > 두 값중 하나가 True이면 True를 반환  
print(True or True)
print(True or False)
print(False or True)
print(False or False)

age = 25
print((age < 15) or (age > 30))

num2 = 30
print((num2 % 10 == 0) or (num2 % 4 == 0))

True
True
True
False
False
True

In [47]:
#not 연산 > True이면 False 반환, False이면 True 반환
print(not True)
print(not False)
print(not(30 > 5))

False
True
False

1) if문

In [31]:
x = 7
if x == 10: # if 옆에 조건식이 참일때만
    print("10입니다.") # 들여쓰기된 부분이 실행됨
print("10이 아닙니다.") #들여쓰기되지 않는 부분이 실행됨

10이 아닙니다.
게임을 한다
공부 시작

In [37]:
today = '월요일'
if today == '토요일':   # SyntaxError: 문법에러 > 콜론 미사용
    print("게임을 한다") # IndentationError : 들여쓰기 에러 > if문 다음문장은 무조건 들여쓰기를 해야함
print("공부 시작")

공부 시작

In [49]:
num1 = -1
if num1 > 3: # 첫번째 if문 조건이 참일 때만 아래로 내려가서 문장을 실행한다
    print("num1은 3보다 큽니다.")
if num1 < 0: # 들여쓰기 위치에 따라 결과값이 달라질 수 있음
    print("num1은 0보다 작습니다!")

num1은 0보다 작습니다!

In [52]:
# 사용자가 입력한 수가 100이면 100이야를 출력, 1000이면 1000이야를 출력
# if문만 사용해서 출력

num = int(input("숫자 입력: "))
if num == 100:
    print("100이야")
if num == 1000:
    print("1000이야")

숫자 입력: 100
100이야
100이야

2) if~else문

In [63]:
x = int(input("숫자 입력: "))
if x == 10: # if문의 조건식이 참일 때
    print("10입니다.") # 출력됨
else: # if문 옆에 조건식이 거짓일 때 내려옴
    print("10이 아닙니다.") # if문의 조건이 거짓일 때 출력됨

x = int(input("숫자 입력: "))
if x == 5:
    print("5입니다.") 
else: 
    print("5가 아닙니다.")


if x > 3 and x < 7:
    print("3보다 크고 7보다 작습니다.")
else:
    print("3이하 7이상입니다.")

int1 = int(input("정수 입력: "))
if (int1 % 2 == 0 or int1 % 3 == 0):
    print("2와 3으로 나누어 떨어집니다.")
else:
    print("2와 3으로 나누어떨어지지 않습니다.")

숫자 입력: 10
10입니다.
숫자 입력: 4
5가 아닙니다.
3보다 크고 7보다 작습니다.
정수 입력: 7
2와 3으로 나누어떨어지지 않습니다.

3) if elif else문

In [65]:
x = 3
if x == 10:
    print("10입니다.")
elif x == 5:
    print("5입니다.")
else:
    print("숫자가 출력되었습니다.")

숫자가 출력되었습니다.

In [73]:
mart = input("수박 또는 포도 선택:")
if mart == "수박":
    print("수박을 산다.")
elif mart == "포도":
    print("포도를 산다.")
else:
    print("집에 간다.")

수박 또는 포도 선택:키위
집에 간다.