1. '본인 이름', 생년월일(8글자), 'python', '2일차 과제' 출력하기 (변수명 name, birthday, subject, string)

In [2]:
name = '김양진'
birthday = 20010227
subject = 'python'
string = '2일차 과제'
print(name, birthday, subject, string)

김양진 20010227 python 2일차 과제
이름 : 김양진 생일 : 20010227 과목 : python 문자열 : 2일차 과제

1-1) 변수명을 %연산자를 이용해 출력하기

In [25]:
# print('%s' % 'name')
# print('%d' % 'birthday')
# print('%s' % 'subject')
# print('%s' % 'string')
print("이름 : %s 생일 : %d 과목 : %s 문자열 : %s" % (name, birthday, subject, string))

이름 : 김양진 생일 : 20010227 과목 : python 문자열 : 2일차 과제

1-2) '2일차 과제' 문자열에서 '2'만 추출하여 출력하기(마이너스 인덱스 이용)

In [ ]:
print(string[-6])
print(string[-6, string[0]])

2

1-3) 생년월일에서 생일만 추출하여 출력하기(인덱스 슬라이싱 이용)

In [26]:
# print(birthday[4:8:1])
print(string(birthday[4:]))

TypeError: ignored

1-4) 본인 이름에서 뒤에 성을 제외한 '이름'과 python 문자열에서 'yhn'만 추출하여 출력하기(슬라이싱 이용)

In [ ]:
print(name[1:])
print(subject[1::2])

양진
yhn

1-5) 본인이름과 생년월일이 한 줄에 출력되도록 하기(f-stirng 이용)

In [8]:
print(f'내 이름은 {name}이고',f'내 생일은 {birthday}이야')
print(f"{name} {birthday}")

내 이름은 김양진이고 내 생일은 20010227이야
김양진 20010227

2. 정수형 변수 1개 Fasle값이 들어가있는 변수 1개를 사용자로부터 입력받은 다음 정수형은 논리형으로, 논리형은 실수형으로 출력하기
(각 변수는 num1과 bool1로 설정)

In [16]:
num1 = int(input("정수 입력: "))
bool1 = float(input("False 값 입력: "))
print(bool(num1), type(bool(num1)))
print(bool1, type(float(bool1)))

정수 입력: 10
False 값 입력: 0
True <class 'bool'>
0.0 <class 'float'>

In [13]:
num1 = bool(input("정수 입력 :"))
bool1 = float(input("False 값 입력 :"))

print(num1, type(num1))
print(bool1, type(bool1))

정수 입력 :10
False 값 입력 :0
True <class 'bool'>
0.0 <class 'float'>

3. 사용자로부터 2개의 실수를 입력받아서 합계 출력하기, 아래 결과와 동일하게 만들기(의미있는 변수명 2개 선언)

<결과>
첫번째 실수 : 2.35 
두번째 실수 : 1.22
2.35와 1.22의 합은 3.57입니다.
정수는 3입니다.

In [21]:
float1 = float(input("첫번째 실수: "))
float2 = float(input("두번째 실수: "))
print('{}와 {}의 합은 {:.2f}입니다.'.format(float1, float2, float1 + float2))
print('정수는 {}입니다'.format(int(float1+float2)))

첫번째 실수: 2.35
두번째 실수: 1.22
2.35와 1.22의 합은 3.57입니다.
정수는 3입니다

In [22]:
float1 = float(input("첫번째 실수: "))
float2 = float(input("두번째 실수: "))
print(f" {float1}와 {float2}의 합은 {float1 + float2}입니다.")
print("%.2f와 %.2f의 합은 %.2f입니다." %(float1, float2, float1+float2))

첫번째 실수: 2.35
두번째 실수: 1.22
 2.35와 1.22의 합은 3.5700000000000003입니다.
2.35와 1.22의 합은 3.57입니다.

4. 코랩 작성시 텍스트셀에 작성하기(다른 프로그램 이용시 주석으로 처리할것)
파이썬의 출력함수는 ('print()')이고, 파이썬의 입력함수는 ('intput()')입니다.
출력 할 수 있는 방법은 (%연산자), (.format()),(f_string)가 있습니다.
2일차 수업까지 이해도는 (상) 입니다.
2일차 과제까지 난이도는 (하)입니다.